"""Social tools: tasting note sharing and preference statistics."""
import json
import os
from typing import Any, Sequence

import anthropic
from mcp.types import TextContent, Tool

from . import db
from .toolhandler import ToolHandler

_DEFAULT_USER = "default"


class ShareTastingNoteHandler(ToolHandler):
    def __init__(self):
        super().__init__("share_tasting_note")

    def get_tool_description(self) -> Tool:
        return Tool(
            name=self.name,
            description="최근 스캔 결과 또는 직접 입력한 와인 정보로 공유용 테이스팅 노트 카드(마크다운)를 생성합니다.",
            inputSchema={
                "type": "object",
                "properties": {
                    "scan_id": {
                        "type": "integer",
                        "description": "공유할 스캔 ID (get_history에서 확인, 없으면 최근 스캔 사용)",
                    },
                    "wine_name": {
                        "type": "string",
                        "description": "직접 입력 시 와인 이름 (scan_id 없을 때)",
                    },
                    "personal_note": {
                        "type": "string",
                        "description": "개인 테이스팅 노트 (선택)",
                    },
                    "user_id": {"type": "string", "default": "default"},
                },
            },
        )

    def run_tool(self, args: dict[str, Any]) -> Sequence[TextContent]:
        user_id = args.get("user_id", _DEFAULT_USER)
        scan_id = args.get("scan_id")
        wine_name = args.get("wine_name", "")
        personal_note = args.get("personal_note", "")

        wine_info: dict = {}
        score = 0
        grade = ""

        if scan_id:
            history = db.get_history(user_id, limit=100)
            matched = [h for h in history if h["id"] == scan_id]
            if matched:
                h = matched[0]
                wine_info = h.get("wine_info", {})
                score = h.get("score", 0)
                grade = h.get("grade", "")
                wine_name = wine_name or h.get("wine_name", "")
        elif not wine_name:
            # 최근 스캔 사용
            history = db.get_history(user_id, limit=1)
            if history:
                h = history[0]
                wine_info = h.get("wine_info", {})
                score = h.get("score", 0)
                grade = h.get("grade", "")
                wine_name = h.get("wine_name", "")

        if not wine_name and not wine_info:
            return [TextContent(type="text", text=json.dumps(
                {"error": "공유할 와인 정보가 없습니다. scan_id 또는 wine_name을 입력해주세요."},
                ensure_ascii=False
            ))]

        # 테이스팅 노트 카드 생성
        vintage = wine_info.get("vintage", "")
        producer = wine_info.get("producer", "")
        region = wine_info.get("region", "")
        wine_type = wine_info.get("wine_type", "")
        grapes = ", ".join(wine_info.get("grape_variety", []))
        description = wine_info.get("description", "")
        food = ", ".join(wine_info.get("food_pairing", []))
        taste = wine_info.get("taste_profile", {})

        def bar(val, max_val=5):
            if not val:
                return "—"
            filled = int(val)
            return "●" * filled + "○" * (max_val - filled)

        card = f"""# 🍷 테이스팅 노트

## {wine_name}{f' {vintage}' if vintage else ''}

| | |
|---|---|
| **생산자** | {producer or '—'} |
| **원산지** | {region or '—'} |
| **타입** | {wine_type or '—'} |
| **품종** | {grapes or '—'} |

### 테이스트 프로필
| 속성 | 레벨 |
|---|---|
| 당도 | {bar(taste.get('sweetness'))} |
| 산도 | {bar(taste.get('acidity'))} |
| 탄닌 | {bar(taste.get('tannin'))} |
| 바디 | {bar(taste.get('body'))} |

{f'### 설명{chr(10)}{description}{chr(10)}' if description else ''}
{f'### 음식 페어링{chr(10)}{food}{chr(10)}' if food else ''}
{f'### 취향 매칭{chr(10)}**{score}점** {grade}{chr(10)}' if score else ''}
{f'### 나의 노트{chr(10)}{personal_note}{chr(10)}' if personal_note else ''}
---
*Generated by Label Sommelier MCP*"""

        return [TextContent(type="text", text=json.dumps(
            {"card": card, "wine_name": wine_name, "score": score},
            ensure_ascii=False, indent=2
        ))]


class GetPreferenceStatsHandler(ToolHandler):
    def __init__(self):
        super().__init__("get_preference_stats")

    def get_tool_description(self) -> Tool:
        return Tool(
            name=self.name,
            description="지금까지 스캔한 와인 기록을 분석하여 취향 통계 리포트를 생성합니다.",
            inputSchema={
                "type": "object",
                "properties": {
                    "user_id": {"type": "string", "default": "default"},
                },
            },
        )

    def run_tool(self, args: dict[str, Any]) -> Sequence[TextContent]:
        user_id = args.get("user_id", _DEFAULT_USER)
        stats = db.get_stats(user_id)
        pref = db.get_preference(user_id)

        if stats.get("total", 0) == 0:
            return [TextContent(type="text", text=json.dumps(
                {"message": "아직 스캔 기록이 없습니다. scan_wine_label로 라벨을 분석해보세요!"},
                ensure_ascii=False
            ))]

        # AI 인사이트 추가
        key = os.environ.get("ANTHROPIC_API_KEY", "")
        insight = ""
        if key:
            prompt = f"""와인 취향 통계를 분석해서 한국어로 2-3문장 인사이트를 제공해주세요:
- 총 {stats['total']}종 스캔, 평균 매칭 점수 {stats['avg_score']}점
- 최고점 와인: {stats['best_wine']} ({stats['best_score']}점)
- 선호 타입: {stats['favorite_type']}, 선호 원산지: {stats['favorite_region']}
- 타입 분포: {stats['type_distribution']}
- 저장된 취향: {pref if pref else '없음'}
간결하게 인사이트만 반환."""
            try:
                client = anthropic.Anthropic(api_key=key)
                resp = client.messages.create(
                    model="claude-haiku-4-5-20251001",
                    max_tokens=300,
                    messages=[{"role": "user", "content": prompt}],
                )
                insight = resp.content[0].text.strip()
            except Exception:
                pass

        result = {**stats, "ai_insight": insight, "saved_preference": pref}
        return [TextContent(type="text", text=json.dumps(result, ensure_ascii=False, indent=2))]
